espeak-bot:
  restart: always
  image: pando85/espeak-bot
  ports:
     - "5000:8443"
  volumes:
    - ./cert.pem:/tmp/cert.pem:ro
  environment:
    - BOT_TOKEN= Telegram Bot API token
    - BOT_URL= Telegram Bot URL
    - CERTIFICATE_PATH=/tmp/cert.pem
